apps:
- name: delivery-app
  cwd: ./
  script: npm
  args: "run dev"
  exec_mode: cluster
  instances: 3
  max_restarts: 3
  max_memory_restart: 500M
  watch: true
  env:
    NODE_ENV: development
    PORT: 3000
